### ISSUE TITLE
Using `node -r @swc/register` and `require("@swc/register")` no longer work

### ISSUE THREAD

**Issue by thecrypticace** [swc-project/register#17]
Hi! Looking into some test failures after upgrading and it seems that swc/register no longer performs the registration automatically but relies on a function to be called.

This is due to the removal of the `register()` call in https://github.com/swc-project/register/pull/14. This broke swc-node but it was fixed in 0.1.9. Was the removal intentional?  And is `node -r @swc/register` no longer supported in lieu of having to use swc-node?

I created a reproduction here which showcases the behavior change from 0.1.7 to 0.1.9:
https://github.com/thecrypticace/swc-register-issue

**Comment by pedropalhari** [comment]
Pinging in, `swc-node` is working flawlessly with a `.swcrc`, but the register hook is failing hard.

For anyone that want a drop-in replacement, [tsm](https://www.npmjs.com/package/tsm) is a great package (it uses esbuild). I have just moved from it to `@swc/register` as `swc` is faster, but will have to rollback.

The whole `swc` is expected to be much greater than `tsm` though. The momentum on it is great.

**Comment by ide** [comment]
The one-line workaround is to make a file that runs `register()` and then require that instead.

```js
// swc-register.js
require('@swc/register)();
```
```bash
node --require ./swc-register ...
```

**Comment by zen0wu** [comment]
this seems trivial to fix right? I was just considering moving to swc from esbuild yday and found out about this.
